### PR TITLE
add point_class_add

### PR DESCRIPTION
**Pull request by zhuomingliang**

### CODE REVIEW

**Comment by japhb** [comment]
(Apologies for the delay, I've been rather sick.)

I'd like a few changes before I merge, if you're willing:

* Rename the files to `luajit-point-class-add-*variant*`, where the *variant* is a one or two word description of what is special about this version of the benchmark (e.g. `luajit-point-class-add-named-build-bless` for the variant that uses named parameters to `BUILD()` and blesses in the `add()` method; try to use equivalent names between nqp and perl6.
* Merge the big comment blocks at the top of each file into a `luajit-point-class-add-README`, with all results from all variants represented in the comparison table (and remove all the extra verbiage from the individual files).
* Use results from the same system in the comparison table; showing your timings on your system versus Mike's values on his system doesn't compare well, especially since he doesn't specify what his system actually *is*; you should specify what your test system is.
* Add relevant entries to `minibenchmarks.pl`.
* (Optional!) Add perl5 equivalents.

**Comment by zhuomingliang** [comment]
Hello,
I'm not good at naming a good name for these *variant*, feel free to change to whatever name you like. :P 
About timings, I've tested luajit is 0.2s on my system, so I consider others are similar result. Actually, I don't care others, I only care about luajit/C++, and Java, which has JIT too.

**Comment by japhb** [comment]
OK, understood about feeling uncomfortable about the variant naming; I can do that post-merge.  Can you do the other things on the list and update the PR?  That will save me some time I'd rather spend on some threading tests.

For the README, since you tested the luajit timings on your system, I'd say just separate the timings Mike Pall had from the timings you found, and include your luajit timing in with your NQP/Rakudo timings, so that people can see the two tables are roughly but not exactly comparable.

**Comment by zhuomingliang** [comment]
Hello, I add a new commit, thanks.

**Pull request merged**
